#!/usr/bin/env bash

REPO_DIR="$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )")"
export QMK_HOME="$REPO_DIR/qmk_firmware"

function qmk_setup() {
  brew install qmk/qmk/qmk
  qmk setup
}

function qmk_clone() {
  local keyboard=$1
  local destination="$REPO_DIR/$2"

  cp -r "$QMK_HOME/keyboards/$keyboard/keymaps/default" "$destination"

  echo "$keyboard" > "$destination/KEYBOARD"
}

function qmk_compile() {
  local keyboard=$1

  if [ ! -d "$keyboard" ]; then
    echo "unknown keyboard: $keyboard"
    exit 1
  fi

  local qmk_keyboard_name=$(cat "$keyboard/KEYBOARD")
  local qmk_keymaps_dir="$QMK_HOME/keyboards/$qmk_keyboard_name/keymaps"
  local keymap_name="$USER"

  ln -sf "$keyboard" "$qmk_keymaps_dir/$keymap_name"

  echo "compiling $keyboard..."
  qmk compile -kb "$qmk_keyboard_name" -km "$keymap_name"
}

function qmk_flash() {
  local keyboard=$1

  if [ ! -d "$keyboard" ]; then
    echo "unknown keyboard: $keyboard"
    exit 1
  fi

  local qmk_keyboard_name=$(cat "$keyboard/KEYBOARD")

  qmk flash -kb "$qmk_keyboard_name" -km "$USER"
}

function qmk_usage() {
  echo "Usage: ./qmk [command]"
  echo
  echo "Commands:"
  echo "  setup - sets up the repo for the first time"
  echo "  clone [kb name] [destination] - clones a keyboard's default mapping to this repo"
  echo "  compile [mapping dir] - compiles a .hex file for your local mapping"
  echo "  flash [mapping dir] - flashes the compiled .hex file for your local mapping"
}

case $1 in
  setup)
    qmk_setup
    ;;
  clone)
    qmk_clone $2 $3
    ;;
  compile)
    qmk_compile $2
    ;;
  flash)
    qmk_flash $2
    ;;
  *)
    qmk_usage
    ;;
esac
